services:
  c3s:
    container_name: c3s
    image: c3s-lab:prod
    build: 
      context: ./
      dockerfile: ./docker/c3s-lab/Dockerfile
      target: deploy
    # volumes:
    #   - ./dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      # - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend-net

networks:
  frontend-net:
    name: pybossa-frontend-net

