services:
  c3s:
    container_name: c3s
    build: 
      context: ./
      dockerfile: ./docker/c3s-lab/Dockerfile
      target: deploy
    restart: always
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf