services:
  csz-lab:
    image: csz-lab:dev
    build: 
      args:
        ENV_FILE_NAME: dev.env.js
    env_file:
      - ./config/env/.env.dev
    networks:
      - frontend-net


networks: 
  frontend-net:
    name: lab-web-net
