services:
  csz-lab:
    container_name: csz-lab
    build: 
      context: ./
      dockerfile: ./docker/csz-lab/Dockerfile
      target: deploy
    restart: always
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf