services:
  c3s:
    image: c3s-lab:prod
    build: 
      context: ./
      dockerfile: ./docker/c3s-lab/Dockerfile
      target: deploy
    ports:
      - 80:80
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - ./config/env/.env.deploy